### ISSUE TITLE
flac support

### ISSUE THREAD

**Issue by atisharma** [rfunk/slimp3slave#1]
This great little player cannot, as I understand it, handle FLAC, since the original slimp3 hardware did not, so the server will not serve the files.
Since slimp3slave simply pipes to the player, I am wondering if anybody has managed to play flacs successfully.

**Comment by atisharma** [comment]
I'm now able to play flac by piping to mpv
   -c "mpv - --really-quiet --no-cache"

**Comment by rfunk** [comment]
The server should be able to recognize that this client is incapable of playing flacs (like any slimp3), and transcode them server-side, if you have the flac software installed. On my system /etc/squeezeboxserver/convert.conf and custom-convert.conf are the files defining this conversion.

**Comment by atisharma** [comment]
It does indeed transcode once I allowed transcoding. Thanks.
